#!/bin/bash
# GitHub Secrets 设置指南

echo "🔐 GitHub Secrets 设置指南"
echo "================================"
echo ""
echo "由于 GitHub 不允许创建以 'GITHUB_' 开头的 Secret 名称，"
echo "我们使用以下名称："
echo ""
echo "📋 需要设置的 Secrets："
echo ""
echo "1. BOT_TOKEN"
echo "   值: 你的 Telegram Bot Token"
echo "   示例: 123456789:ABCdefGHIjklMNOpqrsTUVwxyz"
echo ""
echo "2. CHAT_ID" 
echo "   值: 你的 Telegram Chat ID"
echo "   示例: -1002587693096"
echo ""
echo "3. GITHUB_TOKEN (可选)"
echo "   值: 你的 GitHub Personal Access Token"
echo "   用途: 获取 GitHub 活动数据，避免 API 限制"
echo ""
echo "4. GH_USERNAME"
echo "   值: 你的 GitHub 用户名"
echo "   示例: your-github-username"
echo ""
echo "🔧 设置步骤："
echo "1. 进入你的 GitHub 仓库"
echo "2. 点击 Settings → Secrets and variables → Actions"
echo "3. 点击 'New repository secret'"
echo "4. 逐一添加上述 4 个 secrets"
echo ""
echo "💡 获取 GitHub Token 的方法："
echo "1. 访问 GitHub.com → Settings → Developer settings"
echo "2. 点击 Personal access tokens → Tokens (classic)"
echo "3. 点击 Generate new token (classic)"
echo "4. 选择 'public_repo' 权限即可"
echo ""
echo "✅ 设置完成后，可以在 GitHub Actions 页面手动触发测试"
